apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: nextcloud-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://nextcloud.github.io/helm/'
    # targetRevision: 2.12.2
    targetRevision: 2.14.0
    chart: nextcloud
    helm:
      valueFiles: []
      parameters:
        - name: hpa.enabled
          value: "false"
        - name: hpa.minPods
          value: "1"
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: "10Gi"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
